### ISSUE TITLE
Won't work on Flutter Web

### ISSUE THREAD

**Issue by cybrox** [javoeria/slack-dart#2]
Hi,

Just a quick feedback as I sadly don't have the time to create a proper PR.

The library does not work for Flutter web. The reason is the [Content-Type header](https://github.com/javoeria/slack-dart/blob/master/lib/src/slack_notifier.dart#L41) that you send.

There has been [a bug in the Slack API for years](https://stackoverflow.com/a/45752919/4989946) that causes the request to fail when it is set, as it is not included in the list of allowed headers returned by the preflight request.

I copy/pasted the code of the module and removed the header. After that, it works fine in Flutter web.

**Comment by jaxnz** [comment]
@cybrox 

Looking at using this plugin, if you remove the header, does it work on other platforms, or only web?

**Comment by cybrox** [comment]
@jaxnz We had tested it on Android and it worked fine. 

Haven't tested it on other platforms. But in general, HTTP requests should be platform independent, so it should work on all of them. I think the Slack API just assumes the Content-Type to be `api/json` by default, as that's what's in their docs.

**Comment by javrosales** [comment]
Hi, sorry for the delay, I just uploaded a new version 1.3.0 with updated headers 😄
