### ISSUE TITLE
Multiple SectionBlock's not supported

### ISSUE THREAD

**Issue by valdero** [javoeria/slack-dart#3]
As you map blocks in https://github.com/javoeria/slack-dart/blob/master/lib/src/slack_notifier.dart#L33 before sending the request, multiple section blocks aren't supported. Same is valid for `DividerBlock`.

See the following example Slack [report type](https://app.slack.com/block-kit-builder/T04AAN315#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22FAILED%20%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Nice!%20%20:raised_hands:%20%20All%20the%20tests%20in%20%3Csuite-name%3E%20passed%20on%20%3Cdevice-name%3E%22%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22:white_check_mark:%20First%20test%20flow%5Cn:x:%20Second%20test%20flow%5Cn:white_check_mark:%20Third%20test%20flow%22%7D%7D%5D%7D) on why this would be needed.

**Comment by javoeria** [comment]
`var block1 = HeaderBlock(text: 'FAILED');`
`var block2 = SectionBlock(text: 'Nice!  :raised_hands:  All the tests in <suite-name> passed on <device-name>"');`

**Comment by javrosales** [comment]
I try to copy your example with the package and it's working.
```
var block1 = HeaderBlock(text: 'FAILED');
var block2 = SectionBlock(text: 'Nice!  :raised_hands:  All the tests in <suite-name> passed on <device-name>"');
var block3 = DividerBlock();
var block4 = SectionBlock(text: ':white_check_mark: First test flow\n:x: Second test flow\n:white_check_mark: Third test flow');
var response = await slack.send('', channel: 'test', blocks: [block1, block2, block3, block4]);
```
