### ISSUE TITLE
"Content type: application/x-www-form-urlencoded" strips special characters from image url

### ISSUE THREAD

**Issue by brendan-dexter** [javoeria/slack-dart#5]
Using `application/x-www-form-urlencoded` as `content-type` in the https request strips special charaters. Maybe consider using `application/json`

### Steps to reproduce:
1. Get a firebase download url (image)
2. Send a message to slack with this image
```dart
final slack = SlackNotifier('WEBHOOK_URL');
slack.send(
  'Hello world',
  channel: 'general',
  iconEmoji: ':chart_with_upwards_trend:',
  username: 'My Bot',
  blocks: [SectionBlock(text: 'Hello world')],
  attachments: [
    Attachment(
      pretext: 'A screenshot of the device when the error occured.',
      imageUrl: 'https://firebasestorage.googleapis.com/v0/b/myproject-app.appspot.com/o/assets%2Fscreenshots%2F1701051323831.png?alt=media&token=74a0ef5a-114b-4227-9609-23a7c002afa6',
    ),
  ],
);
```

### Expected output
- Message should be displayed in slack with image as attachment

**Comment by javrosales** [comment]
Initially the header was json but it was changed due to an issue in Flutter Web (see #2)

**Comment by brendan-dexter** [comment]
I see
How about adding the option to specify this particular header? (e.g as a named parameter; which of course defaults to `application/x-www-form-urlencoded`)
And documentation

I can submit a PR asap if you approve :)

**Comment by javrosales** [comment]
Hi, I just uploaded a new version 1.4.0 with an optional param `httpHeaders` so you can use it with custom headers.
Thanks for using the package! 😄
